hub:
  url: https://scale.ikomia.ai
root_folder:
registry:
  path:
  lazy_load: True
  auto_completion: True
workflow:
  path:
data:
  path:
mlflow:
  tracking_uri: http://localhost:5000
  artifact_uri:
  store_uri:
tensorboard:
  tracking_uri: http://localhost:6006
  log_uri:
